### ISSUE TITLE
Re-diseño de paneles

### ISSUE THREAD

**Issue by krypt97** [work-teams/software-quality#24]
Re-diseño de paneles según nueva imagen enviada por WhasppApp.
Así como la paleta de colores enviada.

**Comment by AlexTprog** [comment]
## Referencia
![imagen](https://user-images.githubusercontent.com/67795249/126104805-1554cde7-8f44-4de6-9192-8888786be07a.png)
## Colores:
|Codigo|Img|
|-|-|
|#2c509a|![imagen](https://user-images.githubusercontent.com/67795249/126105080-09b6afc6-f3c9-4bfd-b807-4caf60aeb3f3.png)
|#ffffff|![imagen](https://user-images.githubusercontent.com/67795249/126105137-288cd3b4-7852-4ae3-9657-dd568442aed6.png)|
|#28237f|![imagen](https://user-images.githubusercontent.com/67795249/126105243-8ff2e880-638e-4497-bd69-fd2f1ae370a5.png)|
|#3285cb|![imagen](https://user-images.githubusercontent.com/67795249/126105330-bb2f01bb-ffb1-4a35-aea8-3c8eb2a9c240.png)|
